#spring:
#  main:
#    allow-circular-references: true
xbhel:
  file:
    upload:
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 20KB
      file-count-size: 100
      resolve-lazily: true
      location: /download/upload
      temp-location: /downloads/tmp
      file-type-pattern: '\\.(png|jpg|txt|word|xlsx|7z|zip|md)'
      file-name-pattern: '^[A-Za-z0-9\\-_.]+$'
